name: tower_war_patched
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/adil192/tower_war_patched
publish_to: 'none'

environment:
  sdk: ^3.3.0

dependencies:
  pool: ^1.5.1
  http: ^1.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
